### ISSUE TITLE
Introductory mapping exercise

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/caasi-help-desk#28]
## Context

Related to https://github.com/Police-Data-Accessibility-Project/data-projects/issues/17

We have prior analysis done in this repository: [mj-decriminalization/analysis/grief to action/Final_Marijuana_Visualization.ipynb](https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/blob/main/mj-decriminalization/analysis/grief%20to%20action/Final_Marijuana_Visualization.ipynb)

This issue is about doing some basic mapping and getting familiar with the tools in the process. We will mostly be stealing and modifying code from similar projects / chatgpt, so python knowledge is not critical.

### Research

- [x] check out the source data for [arrests](https://data.wprdc.org/dataset/arrest-data/resource/e03a89dd-134a-4ee8-a2bd-62c40aeebc6f?inner_span=True) and [citations](https://data.wprdc.org/dataset/non-traffic-citations)
- [x] read about [Bokeh and Python](https://towardsdatascience.com/creating-an-interactive-map-in-python-using-bokeh-and-pandas-f84414536a06) or mapping using python notebooks in general

### Getting started / environment setup

- [x] download [pycharm](https://www.jetbrains.com/pycharm/), an "IDE" / code editor geared toward python projects
- [x] install [github desktop](https://desktop.github.com/download/) and clone this repository
- [x] open the above file in pycharm, and "run" it to verify that the analysis is generated as it looks in the web version linked above. note that it references a file in github with merged arrests and citations.
- [x] make a new branch in github called `mj-mapping`, so that your changes are contained to that branch
- [x] check off these tasks and leave a comment checking in when this is complete, or comment if you have issues along the way!

### Mapping data
- [x] grab the new fall 2024 template file once https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/pull/29 is merged
- [x] in your copy of the file, delete everything after the line containing `mj_data_df = pd.read_csv(url, low_memory = False)`
- [x] see if you can modify the file using research about bokeh and [these chat gpt suggestions](https://chatgpt.com/share/66e9bc6b-d6b4-8007-b27b-5935e4e575a8) to make _literally any kind of map appear_ with data from the spreadsheet
   - I'm anticipating you will get stuck here, and we can figure out what's next.
   - use `X` and `Y` columns for location, and `record_type` for arrests vs citations
- next steps TBD; likely will involve comparing police zones, or overlaying arrests and citations in a `heatmap` across pittsburgh with zone or neighborhood overlays

**Comment by mjjacobs13** [comment]
The file is not working in PyCharm, I'm getting error messages.

**Comment by mjjacobs13** [comment]
Everything else is complete!

**Comment by josh-chamberlain** [comment]
@mjjacobs13 once you are able to successfully open the fall 2024 notebook and play around, making a map appear, feel free to mark this task as complete! no need to submit code, and you can move on to #36
