### ISSUE TITLE
Marijuana analysis: citations vs arrests

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/caasi-help-desk#35]
## Context

Part of https://github.com/Police-Data-Accessibility-Project/data-projects/issues/17

## Requirements

Add the charts described below to the Python notebook via Pull Request.

#### Question: how often are citations being used relative to arrests?

- [x] a line plot showing how these numbers change over time
  - an arrest line and a citations line on the same plot

**Comment by josh-chamberlain** [comment]
fixed by #44

**Comment by mjjacobs13** [comment]
Reopening to add neighborhood boundaries to the maps
